### PR TITLE
fix #523 and #522

### LINKED ISSUE #523: Problems with showChanges notification parameter for subscription operations
Hi everyone,

I was playing with NGSI-LD subscriptions when I discovered a new issue. Following the ETSI CIM standard and the specification document for the NGSI-LD API V1.6.1 (i.e., [`ETSI GS CIM 009 V1.6.1`](https://www.etsi.org/deliver/etsi_gs/CIM/001_099/009/01.06.01_60/gs_CIM009v010601p.pdf)), which is supported by Scorpio Context Broker,  according to the section _5.2.14 NotificationParams_ (_Table 5.2.14.1-1: NotificationParams data type definition_ on page 82), there is a notification parameter named _`showChanges`_ that _"If true the previous value (previousValue) of Properties or languageMap (previousLanguageMap) of Language Properties or object (previousObject) of Relationships is provided in addition to the current one. This requires that it exists, i.e. in case of modifications and deletions, but not in the case of creations."_. I've checked that when you create a simple subscription with the _`showChanges`_ notification parameter and update the content or a particular Property of the Entity for which the subscription is generated, both the previous value and the new value of the Properties appear. However, there are problems when the Property includes additional metadata (i.e., Property of Property) or when you combine this _`showChanges`_ notification parameter with the _`sysAttrs`_ notification parameter (also described in _Table 5.2.14.1-1: NotificationParams data type definition_ on page 82 and aforementioned in a previous issue #522).

Let me reproduce all the process:

**Environment**
- scorpiobroker/all-in-one-runner:java-kafka-latest (using the sample [_docker-compose_](https://github.com/ScorpioBroker/ScorpioBroker/blob/development-quarkus/compose-files/docker-compose-java-aaio-kafka.yml) file found in the official Scorpio Context Broker GitHub repository)

**Steps to reproduce**
Creating a subscription to a sample `TemperatureSensor` NGSI-LD Entity with the _`showChanges`_ and  _`sysAttrs`_ notification parameters:
```
curl --location --request POST 'localhost:9090/ngsi-ld/v1/subscriptions/' \
--header 'Content-Type: application/json' \
--header 'Link: <https://fiware.github.io/data-models/full-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
--data-raw '{
    "id": "urn:ngsi-ld:Subscription:TemperatureSensor",
    "type": "Subscription",
	"entities": [{
		"type": "TemperatureSensor"
     }],
    "description": "On-change subscription to TemperatureSensor entities for changes within temperature property.",
    "watchedAttributes": ["temperature"],
    "notification": {
           "endpoint": {
		   "uri": "http://consumer:8082/notify",
		   "accept": "application/json"
           },
           "showChanges": true,
           "sysAttrs": true
    }
}'
```
If we request all the committed subscriptions with the following query:
```
curl --location 'http://localhost:9090/ngsi-ld/v1/subscriptions/' \
--header 'Accept: application/json' \
--header 'Link: <https://fiware.github.io/data-models/full-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' 
```
, the regarding response body is the following:
```
[
    {
        "id": "urn:ngsi-ld:Subscription:TemperatureSensor",
        "type": "Subscription",
        "description": "On-change subscription to TemperatureSensor entities for changes within temperature property.",
        "entities": [
            {
                "type": "TemperatureSensor"
            }
        ],
        "notification": {
            "endpoint": {
                "accept": "application/json",
                "uri": "http://notifier-consumer:8082/notify"
            },
            "format": "normalized",
            "showChanges": true,
            "sysAttrs": true
        },
        "timesFailed": 0,
        "timesSent": 0,
        "watchedAttributes": [
            "temperature"
        ],
        "status": "active"
    }
]
```
Creating a sample `TemperatureSensor` NGSI-LD Entity with a `temperature` Property that includes an _`unitCode`_ attribute as additional metadata to indicate the unit of measurement of the temperature value:
```
curl --location 'http://localhost:9090/ngsi-ld/v1/entities/' \
--header 'Content-Type: application/json' \
--header 'Link: <https://fiware.github.io/data-models/full-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
--data '{
    "id": "urn:ngsi-ld:TemperatureSensor:1",
    "type": "TemperatureSensor",
    "temperature": {
        "type": "Property",
        "value": 27.9,
        "unitCode": "CEL"
    }
}'
```
, the first notification received by the consumer is the following one:
```
{'id': 'urn:ngsi-ld:TemperatureSensor:1', 'type': 'TemperatureSensor', 'temperature': {'type': 'Property', 'createdAt': '2024-02-02T11:01:06Z', 'value': 27.9, 'modifiedAt': '2024-02-02T11:01:06Z', 'unitCode': 'CEL'}, 'createdAt': '2024-02-02T11:01:06Z', 'modifiedAt': '2024-02-02T11:01:06Z'}
```
The notification includes the _`createdAt`_ and _`modifiedAt`_ attributes thanks to the _`sysAttrs`_ notification parameter, and the _`unitCode`_ attribute is included within the `temperature` Property. But if we commit a Partial Attribute Update for the `temperature` property:
```
curl --location --request PATCH 'http://localhost:9090/ngsi-ld/v1/entities/urn:ngsi-ld:TemperatureSensor:1/attrs/temperature' \
--header 'Content-Type: application/json' \
--header 'Link: <https://fiware.github.io/data-models/full-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
--data '{
    "type":"Property", 
    "value": 29.9, 
    "unitCode": "CEL"
}'
```
, the second notification received by the consumer is the following one:
```
{'id': 'urn:ngsi-ld:TemperatureSensor:1', 'type': 'TemperatureSensor', 'temperature': {'type': 'Property', 'previousValue': 27.9, 'value': 29.9}, 'createdAt': '2024-02-02T11:01:06Z', 'ngsi-ld:modifiedAt': {'type': 'DateTime'}}
```
As we can see, even though both the _`value`_ and _`previousValue`_ of the `temperature` Property are displayed, the value of the _`modifiedAt`_  attribute is not updated accordingly (i.e., the notification display `'ngsi-ld:modifiedAt': {'type': 'DateTime'}`), and the _`unitCode`_ attribute disappears from the `temperature` Property.

Thanks again!

Dani

### PR DESCRIPTION
**Pull request by vivekNEC**

### CODE REVIEW

File: SubscriptionManager/src/main/java/eu/neclab/ngsildbroker/subscriptionmanager/service/SubscriptionService.java [hunk 1]
```diff
@@ -206,6 +208,22 @@ private static void addProperty(Map<String, Object> resultMap, String key, Objec
...
+			propertyMap.put(NGSIConstants.CREATEDAT,
+					((List<Map<String, Object>>) newValue).get(0).get(NGSIConstants.NGSI_LD_CREATED_AT));
+		}
+		if (((List<Map<String, Object>>) newValue).get(0).containsKey(NGSIConstants.NGSI_LD_MODIFIED_AT)) {
+			propertyMap.put(NGSIConstants.QUERY_PARAMETER_MODIFIED_AT,
+					((List<Map<String, Object>>) newValue).get(0).get(NGSIConstants.NGSI_LD_MODIFIED_AT));
+		}
+		if (((List<Map<String, Object>>) newValue).get(0).containsKey(NGSIConstants.NGSI_LD_PROVIDED_BY)) {
+			propertyMap.put(NGSIConstants.PROVIDED_BY,
+					((List<Map<String, Object>>) newValue).get(0).get(NGSIConstants.NGSI_LD_PROVIDED_BY));
```
Comment (amitrnec) [inline SubscriptionManager/src/main/java/eu/neclab/ngsildbroker/subscriptionmanager/service/SubscriptionService.java:225]: Please validate this condition in all cases.

**Review by amitrnec — APPROVED** [review]

**Review by ScorpioBroker — APPROVED** [review]
