### PR TITLE
Bug fix #389

### LINKED ISSUE #389: Error when testing connectivity using limit=0 and count=true
I'm currently testing the [ngsildclient](https://github.com/Orange-OpenSource/python-ngsild-client) which makes a request to the NGSI-LD server to test for connectivity. The request sent is 
```
GET http://scorpio.mydomain.com/ngsi-ld/v1/entities?type=None&limit=0&count=true
```
It reports an error, that seems to be caused by PostSQL.

```
HTTP/1.1 500 Internal Server Error
content-length: 141
connection: close
Content-Type: application/json

{
  "detail": "ERROR: syntax error at or near \"{\" (42601)",
  "type": "https://uri.etsi.org/ngsi-ld/errors/InternalError",
  "title": "Internal error"
}
```

If you modify the URL to include `limit=1` there is no problem.

However it seems that `limit=0&count=true` is supported by the spec and even by Scorpio as if I launch the following request:

```
GET http://scorpio.mydomain.com/ngsi-ld/v1/entities?type=None&limit=0
```
I get the following response, which seems it is considered within the code.

```
HTTP/1.1 400 Bad Request
content-length: 142
connection: close
Content-Type: application/json

{
  "detail": "limit can only be 0 if count is activated",
  "type": "https://uri.etsi.org/ngsi-ld/errors/BadRequestData",
  "title": "Bad Request Data."
}
```

Thanks for the work done.

### PR DESCRIPTION
**Pull request by brijeshnec**

### CODE REVIEW

File: QueryManager/src/main/java/eu/neclab/ngsildbroker/queryhandler/services/QueryService.java [hunk 1]
```diff
@@ -181,6 +181,7 @@ private Uni<QueryResult> handleEntityMap(Long resultCount, List<EntityMapEntry>
 
 		if (unis.isEmpty()) {
 			QueryResult q = new QueryResult();
+			if(count) q.setCount(resultCount);
```
Comment (ScorpioBroker) [inline QueryManager/src/main/java/eu/neclab/ngsildbroker/queryhandler/services/QueryService.java]: add curly brackets here. if statements without brackets are generally considered bad practice because of maintainability.

**Review by ScorpioBroker — CHANGES_REQUESTED** [review]
Generally looks good to me. As discussed please add tests for the different types of count requests.

File: QueryManager/src/main/java/eu/neclab/ngsildbroker/queryhandler/services/QueryService.java (hunk 1 above)
Comment (brijeshnec) [reply QueryManager/src/main/java/eu/neclab/ngsildbroker/queryhandler/services/QueryService.java]: done changes as suggested

**Review by amitrnec — APPROVED** [review]

File: QueryManager/src/main/java/eu/neclab/ngsildbroker/queryhandler/services/QueryService.java (hunk 1 above)
Comment (brijeshnec) [reply QueryManager/src/main/java/eu/neclab/ngsildbroker/queryhandler/services/QueryService.java]: Test cases will be added soon in PreviousValue-MergePatch branch

**Review by ScorpioBroker — APPROVED** [review]
